### PR TITLE
fix typo in help command

### PR DESCRIPTION
**Pull request by revolunet**
rackt dev -> rackt server

### CODE REVIEW

**Comment by mzabriskie** [comment]
Thanks for catching this. The indentation on the description appears to be off now. Can you make sure it lines up with the other descriptions?

**Comment by revolunet** [comment]
silly me, fixed

**Comment by revolunet** [comment]
catched by @reggi here : https://github.com/mzabriskie/rackt-cli/issues/16

**Comment by revolunet** [comment]
bump :)

**Pull request merged**
